### ISSUE TITLE
Provides: bundled should not have scl prefix

### ISSUE THREAD

**Issue by pvalena** [mbooth101/spec2scl-old#1]
Provides: %{?scl_prefix}bundled(libname)
should be
Provides: bundled(libname)

**Comment by mbooth101** [comment]
As it says at the top, this project is a fork of https://bitbucket.org/bkabrda/spec2scl.git -- you may want to report this there...

**Comment by pvalena** [comment]
Already did, just missed the sign first time.

Thank you.

Pavel Valena
Associate Software Engineer
Brno, Czech Republic

RED HAT | TRIED. TESTED. TRUSTED.
All of the airlines in the Fortune Global 500 rely on Red Hat.
Find out why at Trusted | Red Hat

http://www.redhat.com/en/about/trusted

----- Original Message -----

**Comment by mbooth101** [comment]
Great, thanks :-)
